version: '3.9'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: php
      MYSQL_USER: user1
      MYSQL_PASSWORD: MaNF48Fc
      MYSQL_ROOT_PASSWORD: MaNF48Fc
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    image: php:7.4-apache
    ports:
        - "80:80"
    volumes:
        - ./src:/var/www/html
    depends_on:
        - db
    command: >
        bash -c "apt-get update && docker-php-ext-install mysqli && apache2-foreground"

volumes:
  db_data: