version: '3'

services:
  web:
    image: php:7.4-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user1
      MYSQL_PASSWORD: MaNF48Fc
      MYSQL_DATABASE: php
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MaNF48Fc
      MYSQL_DATABASE: php
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  src: