version: '3'

services:
  web:
    image: misscod10/apache-php-mysql:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./db_data:/var/lib/mysql
volumes:
  db_data:
  src: