version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MaNF48Fc
      MYSQL_DATABASE: mysql
      MYSQL_USER: user1
      MYSQL_PASSWORD: MaNF48Fc
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: php:apache
    restart: always
    volumes:
      - web_data:/var/www/html
    ports:
      - "80:80"
    links:
      - db:mysql

volumes:
  db_data:
  web_data:
